theme: jekyll-theme-primer
title: Trump Tweet VIX
description: Predcit VIX Changes Using Trump Tweets
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
remote_theme: pmarsceill/just-the-docs # andrewbanchich/forty-jekyll-theme # #Simpleyyt/jekyll-jacman #alexanderussell/progress-for-jekyll/ 
search_enabled: true
exclude: ["*.json", "*.csv", "*.ipynb", "*.pdf", "papers/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]
aux_links:
  "Trump Tweet VIX on Github":
      - "//github.com/adilbhatia98/CS109A-Group-3"
